// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWeePMe52NBCfqywwqSr-zPhIeQ1kUFV4',
    appId: '1:444698868088:web:f5fbb89e6c51258b70b08d',
    messagingSenderId: '444698868088',
    projectId: 'servi-sur-dashboard',
    authDomain: 'servi-sur-dashboard.firebaseapp.com',
    storageBucket: 'servi-sur-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vLyYPQYuGG3suG_wD0owlqLWhdFXYqo',
    appId: '1:444698868088:android:2d119a59da3e8d0970b08d',
    messagingSenderId: '444698868088',
    projectId: 'servi-sur-dashboard',
    storageBucket: 'servi-sur-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-JVjoTPM7QQuceu9qPcHV0p83z7Sie7I',
    appId: '1:444698868088:ios:46a800b7a0daedcc70b08d',
    messagingSenderId: '444698868088',
    projectId: 'servi-sur-dashboard',
    storageBucket: 'servi-sur-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.serviSur',
  );
}
